import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // A leading underscore marks a name as unused on purpose: a parameter a
    // signature requires (a capability's prompt env, a mock matching `put()`).
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_", destructuredArrayIgnorePattern: "^_" },
      ],
    },
  },
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the Workflow SDK (next.config.ts, vitest.workflow.config.ts).
    ".workflow-data/**",
    ".livecheck/**",
    ".workflow-vitest/**",
    ".swc/**",
    "src/app/.well-known/workflow/**",
    // Agent worktrees: full checkouts of this repo nested inside it.
    ".claude/**",
    // Marketing media (media/product-video): its own package.json and toolchain.
    "media/**",
  ]),
]);

export default eslintConfig;
