import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the Workflow SDK (next.config.ts, vitest.workflow.config.ts).
    ".workflow-data/**",
    ".livecheck/**",
    ".workflow-vitest/**",
    ".swc/**",
    "src/app/.well-known/workflow/**",
  ]),
]);

export default eslintConfig;
