// @vitest-environment node
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { buildPdf } from "../../../test/fixtures/manuals/build-pdf";
import { FIXTURES, type FixtureName } from "../../../test/fixtures/manuals/fixtures";
import {
  buildLines,
  extractManual,
  EXTRACTOR_VERSION,
  inferHeadings,
  isBarePageNumber,
  isJunkBookmark,
  joinHyphenation,
  pageText,
  removeRunningLines,
  usableBookmarks,
  type PageLine,
} from "./extract";

/**
 * The manual extractor (manual text spec §3.2, §10) over the committed fixture
 * PDFs in `test/fixtures/manuals/` — generated by `generate.ts` from
 * `fixtures.ts`, so each one's content is known exactly.
 */

function fixture(name: FixtureName): Uint8Array {
  return new Uint8Array(readFileSync(join(process.cwd(), "test/fixtures/manuals", name)));
}

describe("the fixtures", () => {
  it("are the committed output of fixtures.ts (run generate.ts after changing it)", () => {
    for (const [name, build] of Object.entries(FIXTURES)) {
      expect(Buffer.from(fixture(name as FixtureName)).equals(Buffer.from(build())), name).toBe(true);
    }
  });
});

describe("extractManual", () => {
  it("reads a PDF with bookmarks: pages, outline resolved to pages and levels, and its title", async () => {
    const result = await extractManual(fixture("outline.pdf"));
    expect(result).toMatchObject({ status: "ready", reason: null, pageCount: 4, outlineSource: "pdf", title: "Acme Laser 40 User Manual" });
    expect(result.outline).toEqual([
      { title: "Introduction", page: 1, level: 1 },
      { title: "Specifications", page: 2, level: 1 },
      { title: "Electrical", page: 3, level: 2 },
      { title: "Maintenance", page: 4, level: 1 },
    ]);
    expect(result.pages.map((page) => page.pageNumber)).toEqual([1, 2, 3, 4]);
    expect(result.pages[1].text).toBe(
      [
        "Specifications",
        "Work area: 400 x 300 mm",
        "Laser power: 40 W CO2 tube",
        "Maximum engraving speed: 600 mm/s",
        "Positioning accuracy: 0.01 mm",
        "Supported files: SVG, DXF, PDF, PNG",
        "Weight: 32 kg",
      ].join("\n")
    );
  });

  it("drops the running header and the page-number footer, and joins a word hyphenated across lines", async () => {
    const result = await extractManual(fixture("outline.pdf"));
    const all = result.pages.map((page) => page.text).join("\n");
    expect(all).not.toContain("Acme Laser 40 - User Manual");
    expect(all).not.toMatch(/Page \d/);
    expect(result.pages[0].text).toContain("beside the machine for calibration and cleaning reference.");
    // A range is not hyphenation.
    expect(result.pages[2].text).toContain("Input voltage: 110-120 V AC, 60 Hz");
  });

  it("infers headings from font size when the PDF has no bookmarks", async () => {
    const result = await extractManual(fixture("no-outline.pdf"));
    expect(result.status).toBe("ready");
    expect(result.outlineSource).toBe("inferred");
    // The 24 pt title is used once, so it does not push the 20 pt chapters down a level.
    expect(result.outline).toEqual([
      { title: "Acme Laser 40", page: 1, level: 1 },
      { title: "Getting started", page: 1, level: 1 },
      { title: "Technical data", page: 2, level: 1 },
      { title: "Machine", page: 2, level: 2 },
      { title: "Care and cleaning", page: 3, level: 1 },
      { title: "Lens and mirrors", page: 3, level: 2 },
    ]);
  });

  it("keeps printed page labels that differ from the page number, and no outline when there is nothing to infer", async () => {
    const result = await extractManual(fixture("page-labels.pdf"));
    expect(result.pages.map((page) => page.label)).toEqual(["i", "ii", "3-1", "3-2"]);
    expect(result.outline).toEqual([]);
    expect(result.outlineSource).toBe("none");
  });

  it("classifies a scan — under 100 characters a page — as no_text and keeps no pages", async () => {
    const result = await extractManual(fixture("scanned.pdf"));
    expect(result).toEqual({
      status: "no_text",
      reason: "no_text_layer",
      pageCount: 3,
      pages: [],
      outline: [],
      outlineSource: "none",
      title: null,
    });
  });

  it("fails an encrypted file, a corrupt one, and an empty one, without throwing", async () => {
    expect(await extractManual(fixture("encrypted.pdf"))).toMatchObject({ status: "failed", reason: "encrypted", pageCount: null });
    expect(await extractManual(fixture("corrupt.pdf"))).toMatchObject({ status: "failed", reason: "corrupt" });
    expect(await extractManual(new Uint8Array())).toMatchObject({ status: "failed", reason: "corrupt" });
  });

  it("fails as too_large over the byte, page or time limit", async () => {
    const bytes = fixture("outline.pdf");
    expect(await extractManual(bytes, { maxBytes: 100 })).toMatchObject({ status: "failed", reason: "too_large" });
    expect(await extractManual(bytes, { maxPages: 3 })).toMatchObject({ status: "failed", reason: "too_large", pageCount: 4 });
    const long = buildPdf({
      pages: Array.from({ length: 400 }, (_, n) => ({ lines: [{ text: `Page ${n} of a long manual with some body text on it.`, y: 700 }] })),
    });
    expect(await extractManual(long, { timeoutMs: 5 })).toMatchObject({ status: "failed", reason: "too_large" });
  });

  it("leaves the caller's bytes usable (pdf.js takes a copy)", async () => {
    const bytes = fixture("outline.pdf");
    await extractManual(bytes);
    expect(bytes.byteLength).toBeGreaterThan(0);
    expect((await extractManual(bytes)).status).toBe("ready");
  });

  it("names its version, which is what re-processing keys on", () => {
    expect(EXTRACTOR_VERSION).toMatch(/^unpdf-\d+\/extract-\d+$/);
  });
});

describe("the pieces", () => {
  const line = (text: string, size = 11, y = 0): PageLine => ({ text, size, y });

  it("rebuilds lines from text items: a new line on an end-of-line mark or a baseline move, a space across a gap", () => {
    const lines = buildLines([
      { str: "Work", transform: [11, 0, 0, 11, 72, 700], width: 25, hasEOL: false },
      { str: "area:", transform: [11, 0, 0, 11, 100, 700], width: 25, hasEOL: false },
      { str: "400 mm", transform: [11, 0, 0, 11, 130, 700], width: 30, hasEOL: true },
      { str: "Next", transform: [11, 0, 0, 11, 72, 685], width: 20 },
      { str: "line", transform: [18, 0, 0, 18, 72, 660], width: 20 },
    ]);
    expect(lines).toEqual([
      { text: "Work area: 400 mm", size: 11, y: 700 },
      { text: "Next", size: 11, y: 685 },
      { text: "line", size: 18, y: 660 },
    ]);
  });

  it("removes a line only at a page's edges and only when it repeats on most pages", () => {
    const words = ["alpha", "beta", "gamma", "delta"];
    const pages = words.map((word, n) => [
      line("Manual v2"),
      line(`The ${word} section.`),
      line("Manual v2"),
      line(`More about ${word}.`),
      line(`Rev ${n + 1}`),
      line(`${n + 1}`),
    ]);
    const kept = removeRunningLines(pages);
    // The header (top), "Rev n" and the page number (bottom) go; the same words mid-page stay.
    expect(kept[0].map((l) => l.text)).toEqual(["The alpha section.", "Manual v2", "More about alpha."]);
    // Two pages are too few to call anything a header — but a bare page number still goes.
    expect(removeRunningLines(pages.slice(0, 2))[0].map((l) => l.text)).toEqual(pages[0].map((l) => l.text));
  });

  it("recognises a bare page number", () => {
    for (const text of ["12", "- ii -", "iv", " 3 "]) expect(isBarePageNumber(text), text).toBe(true);
    for (const text of ["12 mm", "Page 3 of 9", "Civic", "ill", ""]) expect(isBarePageNumber(text), text).toBe(false);
  });

  it("joins hyphenation only between letters, and shortens dot leaders", () => {
    expect(joinHyphenation("calibra-\ntion")).toBe("calibration");
    expect(joinHyphenation("110-\n120 V")).toBe("110-\n120 V");
    expect(joinHyphenation("CO2-\nLaser")).toBe("CO2-\nLaser");
    expect(pageText([line("Cleaning the optics ........................ 69")])).toBe("Cleaning the optics … 69");
  });

  it("drops identifier bookmarks, and all of them when most are identifiers", () => {
    expect(isJunkBookmark("_tyjcwt")).toBe(true);
    expect(isJunkBookmark("P322_681_eng")).toBe(true);
    expect(isJunkBookmark("Safety")).toBe(false);
    expect(isJunkBookmark("1.2 Hazards")).toBe(false);
    const entry = (title: string) => ({ title, page: 1, level: 1 });
    expect(usableBookmarks([entry("_a1"), entry("_b2"), entry("Safety")])).toEqual([]);
    expect(usableBookmarks([entry("Safety"), entry("Setup"), entry("_b2")])).toEqual([entry("Safety"), entry("Setup")]);
  });

  it("infers headings: not sentences, joined across two lines, and only the larger sizes when there are too many", () => {
    const body = (n: number) => Array.from({ length: n }, (_, i) => line(`Body text line ${i} with enough words in it.`));
    const pages: PageLine[][] = [
      [line("Owner's Manual", 28), line("IMPORTANT SAFETY", 20), line("INFORMATION", 20), line("Read every warning below before use.", 20), ...body(10)],
      [line("Specifications", 20), line("Machine", 16), ...body(5), line("Materials", 16), ...body(5)],
      [line("Care", 20), line("Lens", 16), line("Belts", 14), ...body(3), line("Rails", 14), ...body(10)],
    ];
    expect(inferHeadings(pages)).toEqual([
      { title: "Owner's Manual", page: 1, level: 1 },
      { title: "IMPORTANT SAFETY INFORMATION", page: 1, level: 1 },
      { title: "Specifications", page: 2, level: 1 },
      { title: "Machine", page: 2, level: 2 },
      { title: "Materials", page: 2, level: 2 },
      { title: "Care", page: 3, level: 1 },
      { title: "Lens", page: 3, level: 2 },
      { title: "Belts", page: 3, level: 3 },
      { title: "Rails", page: 3, level: 3 },
    ]);

    // Forty callouts at 13 pt on four pages are not forty headings: only the 20 pt chapter titles are kept.
    const noisy: PageLine[][] = [0, 1, 2, 3].map((p) => [
      line(`Chapter ${p}`, 20),
      ...Array.from({ length: 10 }, (_, i) => line(`Warning ${p}-${i}`, 13)),
      ...body(20),
    ]);
    const inferred = inferHeadings(noisy);
    expect(inferred.map((e) => e.title)).toEqual(["Chapter 0", "Chapter 1", "Chapter 2", "Chapter 3"]);
  });
});
