import { boolean, index, pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { inListCheck } from "./checks.ts";
import { ROLES } from "./vocabulary.ts";

/**
 * Better Auth's four tables (data platform design spec 2026-09-14 §4.2).
 *
 * The library owns these rows: it inserts and updates them through the Drizzle
 * adapter, and nothing in `src/lib/data/` writes them. What *we* own is the
 * shape — the `user.role` CHECK, the indexes, and the fact that `created_by`
 * on every other table now references `user.id` (see `helpers.ts`).
 *
 * **The property keys are load-bearing.** The Drizzle adapter resolves a Better
 * Auth field to a column by looking the *JavaScript property name* up on the
 * table object (`schema[model][field]` in `@better-auth/drizzle-adapter`), so
 * every key here is Better Auth's camelCase field name, exactly. The SQL column
 * names are ours to choose and stay snake_case like the rest of the schema.
 *
 * The field list is taken from the library itself rather than from the docs:
 * `@better-auth/core/dist/db/get-tables.mjs` for the four core tables, and
 * `better-auth/dist/plugins/admin/schema.d.mts` for what the admin plugin adds
 * (`role`, `banned`, `banReason`, `banExpires` on user; `impersonatedBy` on
 * session). The spec says these are generated by `npx @better-auth/cli
 * generate`; that CLI is not a dependency and wants the network, and the
 * generator reads exactly the two modules above. See the Phase 4 amendment.
 *
 * No `updated_at` trigger (migration `0002`) is attached to these tables:
 * Better Auth writes `updatedAt` itself on every update, and a table the
 * library owns should not have a second writer.
 */

/**
 * A person. `role` is the whole authorization story — what each role may do is
 * declared in code (`src/lib/auth/permissions.ts`), not in a table, because the
 * lab decided on 2026-09-14 that admins do not edit permissions at runtime.
 */
export const user = pgTable(
  "user",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    email: text("email").notNull().unique(),
    emailVerified: boolean("email_verified").notNull().default(false),
    image: text("image"),
    // Admin plugin. Nullable because the plugin declares it optional; the
    // default and the `defaultRole: "user"` option both land it as `user`.
    role: text("role").default("user"),
    banned: boolean("banned").default(false),
    banReason: text("ban_reason"),
    banExpires: timestamp("ban_expires", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // A role outside the vocabulary is a bug or a forgery; the database is the
    // last place to catch it, and `can()` grants an unknown role nothing anyway.
    inListCheck("user_role_check", "role", ROLES),
    index("user_email_idx").on(t.email),
  ]
);

/**
 * A live sign-in. **This table is the reason Phase 4 exists**: the session is a
 * row, not a self-describing cookie, so a role change is visible on the
 * person's next request and a ban takes effect immediately (spec §3.4, Goal 3).
 */
export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    token: text("token").notNull().unique(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    // Admin plugin. Unused — v5 never impersonates — but the column has to
    // exist or the plugin's queries reference a column that is not there.
    impersonatedBy: text("impersonated_by"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("session_user_idx").on(t.userId)]
);

/**
 * The link to an external identity provider. For v5 that is Google and nothing
 * else: `providerId` is `"google"` and `accountId` is Google's `sub`. The token
 * columns exist because Better Auth's schema has them; v5 asks for no Google
 * scopes beyond the profile, so they stay empty.
 */
export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
    scope: text("scope"),
    // Password auth is not enabled; the column is part of Better Auth's shape.
    password: text("password"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("account_user_idx").on(t.userId)]
);

/**
 * Short-lived verification values (OAuth state, PKCE verifiers). Rows here are
 * consumed within one handshake and mean nothing afterwards.
 */
export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("verification_identifier_idx").on(t.identifier)]
);
